FileLog = open("Log.txt", "a", encoding="UTF-8")

def InfoToLog(InfoToLog):
    FileLog = open("Log.txt", "a", encoding="UTF-8")
    print("Info saved to log: ", InfoToLog, " :Date " + "HH.MM.SS")
    FileLog.write("HH.MM.SS: " + InfoToLog + '\n')
    
def Encrypting(TransItem):
    TransItem = str(TransItem)
    TransItem = TransItem.upper()
    TransItem = TransItem.replace("^", ">>>")
    TransItem = TransItem.replace("/","->>")
    TransItem = TransItem.replace("*","=>>")
    TransItem = TransItem.replace("+","=>")
    TransItem = TransItem.replace("-","->")
    TransItem = TransItem.replace("0","೧")
    TransItem = TransItem.replace("1","⛡")
    TransItem = TransItem.replace("2","𑇢")
    TransItem = TransItem.replace("3","꘢")
    TransItem = TransItem.replace("4","🜉")
    TransItem = TransItem.replace("5","🝝")
    TransItem = TransItem.replace("6","🝢")
    TransItem = TransItem.replace("7","ꩼ")
    TransItem = TransItem.replace("8","ⅱ")
    TransItem = TransItem.replace("9","ÿ")
    TransItem = TransItem.replace("A","☎")
    TransItem = TransItem.replace("B","#")
    TransItem = TransItem.replace("C",">")
    TransItem = TransItem.replace("D","™")
    TransItem = TransItem.replace("E","↸")
    TransItem = TransItem.replace("F","&")
    TransItem = TransItem.replace("G","9")
    TransItem = TransItem.replace("H","↹")
    TransItem = TransItem.replace("I","⇔")
    TransItem = TransItem.replace("J","✉")
    TransItem = TransItem.replace("K","♜")
    TransItem = TransItem.replace("L","❦")
    TransItem = TransItem.replace("M","|")
    TransItem = TransItem.replace("N","☣")
    TransItem = TransItem.replace("O","➤")
    TransItem = TransItem.replace("P","⛏︎")
    TransItem = TransItem.replace("Q","℥")
    TransItem = TransItem.replace("R","𓆝")
    TransItem = TransItem.replace("S","!")
    TransItem = TransItem.replace("T","₫")
    TransItem = TransItem.replace("U","⅒")
    TransItem = TransItem.replace("W","◲")
    TransItem = TransItem.replace("X","▶")
    TransItem = TransItem.replace("Y","⎔")
    TransItem = TransItem.replace("Z","❂")
    return(TransItem)

def Uncrypting(TransItem):
    TransItem = str(TransItem)
    TransItem = TransItem.upper()
    TransItem = TransItem.replace("+>>>","^")
    TransItem = TransItem.replace("->>","/")
    TransItem = TransItem.replace("=>>","*")
    TransItem = TransItem.replace("=>","+")
    TransItem = TransItem.replace("->","-")
    TransItem = TransItem.replace("೧","0")
    TransItem = TransItem.replace("⛡","1")
    TransItem = TransItem.replace("𑇢","2")
    TransItem = TransItem.replace("꘢","3")
    TransItem = TransItem.replace("🜉","4")
    TransItem = TransItem.replace("🝝","5")
    TransItem = TransItem.replace("🝢","6")
    TransItem = TransItem.replace("ꩼ","7")
    TransItem = TransItem.replace("ⅱ","8")
    TransItem = TransItem.replace("ÿ","9")
    TransItem = TransItem.replace("☎","A")
    TransItem = TransItem.replace("#","B")
    TransItem = TransItem.replace(">","C")
    TransItem = TransItem.replace("™","D")
    TransItem = TransItem.replace("↸","E")
    TransItem = TransItem.replace("&","F")
    TransItem = TransItem.replace("9","G")
    TransItem = TransItem.replace("↹","H")
    TransItem = TransItem.replace("⇔","I")
    TransItem = TransItem.replace("✉","J")
    TransItem = TransItem.replace("♜","K")
    TransItem = TransItem.replace("❦","L")
    TransItem = TransItem.replace("|","M")
    TransItem = TransItem.replace("☣","N")
    TransItem = TransItem.replace("➤","O")
    TransItem = TransItem.replace("⛏︎","P")
    TransItem = TransItem.replace("℥","Q")
    TransItem = TransItem.replace("𓆝","R")
    TransItem = TransItem.replace("!","S")
    TransItem = TransItem.replace("₫","T")
    TransItem = TransItem.replace("⅒","U")
    TransItem = TransItem.replace("◲","W")
    TransItem = TransItem.replace("▶","X")
    TransItem = TransItem.replace("⎔","Y")
    TransItem = TransItem.replace("❂","Z")
    return(TransItem)

def NewEncrypting(TransItem, listcar):
    for i in range(0, len(TransItem), 4):
        listcar = listcar + Encrypting(TransItem[i:i+4])
    return(listcar) 
